# Generated by Django 5.1.2 on 2024-10-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="documents"),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
